---
title: "Additional Environmental Variables for the  \n2024 SEAK Pink Salmon Preseason Forecast"
author: "Sara Miller"
date: "September 25, 2023"
format: pdf
editor: visual
---

# Objective

The overall objective is to examine the correlations between the southeast Alaska (SEAK) pink salmon harvest and variables such as ISTI20_MJJ, CPUEcal, condition residuals from June and July, energy density (kJ/g) in June or July, average zooplankton total water column (ml/m^3^) in May, June, or July, the preferred prey (number/m^3^) in May, June, or July, and the satellite sea surface temperature (SST) variables in SEAK.

# **Variable definitions**

**ISTI20_MJJ:** The average 20-m integrated water column temperature at the eight stations in Icy Strait (Icy Strait and Upper Chatham transects) sampled during the SECM surveys in May, June, and July of each year (in degrees Celsius). The last time the ISTI variable was incorporated in the forecasting process was the 2023 forecast.

**CPUEcal:** The average Ln(CPUE+1) for catches in either June or July, whichever month had the highest average in a given year, where effort was a standard trawl haul. The CPUE data was adjusted using calibration factors to account for differences in fishing power among vessels. The last time the CPUEcal variable was incorporated in the forecasting process was the 2023 forecast.

**Condition**: The average annual residuals derived from the regression of all paired Ln(weights) and Ln(lengths) for pink salmon collected during SECM sampling since 1997 in June and July. The last time the condition residuals were incorporated in the forecasting process was the 2019 forecast.

**Energy Density**: The average energy content (calories/gram wet weight, determined by bomb calorimetry) of subsamples of juvenile pink salmon captured in June or July of each year. The last time the energy density variables were incorporated in the forecasting process was the 2017 forecast (Wertheimer et al. 2018).

Zooplankton metric (**Average Zooplankton Total Water Column**; ml/m$^3$): The average May, June, or July 333-$\mu$m bongo net standing crop (displacement volume divided by water volume filtered, ml/m$^3$), and index of integrated mesozooplankton to 200-m depth (i.e., May, June, or July average zooplankton total water column). The last time the zooplankton metric variables were incorporated in the forecasting process was the 2017 forecast (Wertheimer et al. 2018).

Zooplankton metric (**Preferred Prey**; number/m): The average density (number/m$^3$) of preferred prey available in May, June, or July; an index computed from total density of six zooplankton taxa typically utilized by planktivorous juvenile salmon in summer (Sturdevant et al. 2004) and present in integrated 333-$\mu$m bongo net samples (June Preferred Prey). The last time the zooplankton metric variables were incorporated in the forecasting process was the 2015 forecast (Wertheimer et al. 2015).

## Satellite SST variables

**Icy_Strait_SST_May**: The Icy Strait region encompasses waters of Icy Strait from the east end of Lemesurier Island to a line from Point Couverden south to Point Augusta. This variable is the average SST in May. The last time this variable was incorporated in the forecasting process was the 2023 forecast.

**Icy_Strait_SST_MJJ:** The Icy Strait region encompasses waters of Icy Strait from the east end of Lemesurier Island to a line from Point Couverden south to Point Augusta. This variable is the average SST in May through July. The last time this variable was incorporated in the forecasting process was the 2023 forecast.

**Icy_Strait_SST_AMJ**: The Icy Strait region encompasses waters of Icy Strait from the east end of Lemesurier Island to a line from Point Couverden south to Point Augusta. This variable is the average SST in April through June. The last time this variable was incorporated in the forecasting process was the 2023 forecast.

**Icy_Strait_SST_AMJJ**: The Icy Strait region encompasses waters of Icy Strait from the east end of Lemesurier Island to a line from Point Couverden south to Point Augusta. This variable is the average SST in April through July. The last time this variable was incorporated in the forecasting process was the 2023 forecast.

**Chatham_SST_May**: The Chatham and Icy Straits region encompasses waters of Chatham and Icy Straits east of Lemesurier Island to Point Couverden, and south to the approximate latitude of 56.025 degrees north (roughly Cape Decision off Kuiu Island). This variable is the average SST in May. The last time this variable was incorporated in the forecasting process was the 2023 forecast.

**Chatham_SST_MJJ**: The Chatham and Icy Straits region encompasses waters of Chatham and Icy Straits east of Lemesurier Island to Point Couverden, south to the approximate latitude of 56.025 degrees north (roughly Cape Decision off Kuiu Island). This variable is the average SST in May through July. The last time this variable was incorporated in the forecasting process was the 2023 forecast.

**Chatham_SST_AMJ**: The Chatham and Icy Straits region encompasses waters of Chatham and Icy Straits east of Lemesurier Island to Point Couverden, south to the approximate latitude of 56.025 degrees north (roughly Cape Decision off Kuiu Island). This variable is the average SST in April through June. The last time this variable was incorporated in the forecasting process was the 2023 forecast.

**Chatham_SST_AMJJ**: The Chatham and Icy Straits region encompasses waters of Chatham and Icy Straits east of Lemesurier Island to Point Couverden, south to the approximate latitude of 56.025 degrees north (roughly Cape Decision off Kuiu Island). This variable is the average SST in April through July. The last time this variable was incorporated in the forecasting process was the 2023 forecast.

**NSEAK_SST_May**: The NSEAK region encompasses northern Southeast Alaska from 59.475 to 56.075 degrees north latitude (approximately Districts 9 through 15, and District 13 inside area only; northern Southeast Inside subregion for Southeast Alaska (NSEI)). This variable is the average SST in May. The last time this variable was incorporated in the forecasting process was the 2023 forecast.

**NSEAK_SST_MJJ**: The NSEAK region encompasses northern Southeast Alaska from 59.475 to 56.075 degrees north latitude (approximately Districts 9 through 15, and District 13 inside area only; northern Southeast Inside subregion for Southeast Alaska (NSEI)). This variable is the average SST in May through July. The last time this variable was incorporated in the forecasting process was the 2023 forecast.

**NSEAK_SST_AMJ**: The NSEAK region encompasses northern Southeast Alaska from 59.475 to 56.075 degrees north latitude (approximately Districts 9 through 15, and District 13 inside area only; northern Southeast Inside subregion for Southeast Alaska (NSEI)). This variable is the average SST in April through June. The last time this variable was incorporated in the forecasting process was the 2023 forecast.

**NSEAK_SST_AMJJ**: The NSEAK region encompasses northern Southeast Alaska from 59.475 to 56.075 degrees north latitude (approximately Districts 9 through 15, and District 13 inside area only; northern Southeast Inside subregion for Southeast Alaska (NSEI)). This variable is the average SST in April through July. The last time this variable was incorporated in the forecasting process was the 2023 forecast.

**SEAK_SST_May**: The SEAK region encompasses Southeast Alaska from 59.475 to 54.725 degrees north latitude. This variable is the average SST in May. The last time this variable was incorporated in the forecasting process was the 2023 forecast.

**SEAK_SST_MJJ**: The SEAK region encompasses northern Southeast Alaska from 59.475 to 54.725 degrees north latitude. This variable is the average SST in May through July. The last time this variable was incorporated in the forecasting process was the 2023 forecast.

**SEAK_SST_AMJ**: The SEAK region encompasses Southeast Alaska from 59.475 to 54.725 degrees north latitude. This variable is the average SST in April through June. The last time this variable was incorporated in the forecasting process was the 2023 forecast.

**SEAK_SST_AMJJ**: The SEAK region encompasses Southeast Alaska from 59.475 to 54.725 degrees north latitude. This variable is the average SST in April through July. The last time this variable was incorporated in the forecasting process was the 2023 forecast.

# Results

|                     Parameter                     |    *r*    |  *P*-value  |
|:---------------------------------:|:----------------:|:----------------:|
|                    **CPUEcal**                    | **0.75**  | **\<0.001**|
|                    ISTI20_MJJ                     |   -0.22   |    0.28    |
|                     condition                     |           |            |
|               energy density (June)               |   -0.41   |    0.22    |
|             **energy density (July)**             | **-0.42** |  **0.03**  |
|   avg. zooplankton TWC (May)                      |   0.08    |    0.70    |
|   avg. zooplankton TWC (June)                     |   0.34    |    0.09    |
| **avg. zooplankton TWC (July)**                   | **-0.45** |  **0.02**  |
|               preferred prey (May)                |   -0.29   |    0.15    |
|               preferred prey (June)               |   0.01    |    0.95    |
|               preferred prey (July)               |   -0.26   |    0.21    |
|                  Chatham_SST_MJJ                  |   -0.24   |    0.23    |
|                  Chatham_SST_May                  |   -0.18   |    0.37    |
|                 Chatham_SST_AMJJ                  |   -0.23   |    0.25    |
|                  Chatham_SST_AMJ                  |   -0.23   |    0.27    |
|                Icy_Strait_SST_MJJ                 |   -0.23   |    0.25    |
|                Icy_Strait_SST_May                 |   -0.11   |    0.59    |
|                Icy_Strait_SST_AMJJ                |   -0.20   |    0.32    |
|                Icy_Strait_SST_AMJ                 |   -0.17   |    0.41    |
|                   NSEAK_SST_MJJ                   |   -0.29   |    0.15    |
|                   NSEAK_SST_May                   |   -0.24   |    0.24    |
|                  NSEAK_SST_AMJJ                   |   -0.27   |    0.19    |
|                   NSEAK_SST_AMJ                   |   -0.26   |    0.19    |
|                   SEAK_SST_MJJ                    |   -0.30   |    0.13    |
|                   SEAK_SST_May                    |   -0.23   |    0.25    |
|                   SEAK_SST_AMJJ                   |   -0.28   |    0.17    |
|                   SEAK_SST_AMJ                    |   -0.26   |    0.20    |

: Pearson correlation coefficients for juvenile pink salmon abundance, growth and condition variables, and zooplankton variables (i.e., average zooplankton total water column by month, preferred prey by month) in year y for 1997 to 2023 with adult pink salmon harvest in Southeast Alaska in year y+1. The variables with significant correlations with SEAK pink salmon harvest are in bold text. Total water column (TWC).

# Recomendations

Besides the CPUEcal, ISTI20_MJJ, and the satellite SST variables, include the additional variables (Table 1) in the 2024-forecast model process. First, develop regression models of annual SEAK pink salmon harvest and juvenile salmon CPUE, and then include a temperature variable and the additional biophysical variables (zooplankton metrics, fish condition, fish energy density). To include these additional biophysical parameters, a backward/forward stepwise regression with an alpha value of *P*-value \< 0.05 should be implemented. The second step is to calculate the Akaike Information Criterion, corrected for small sample sizes (AICc values; Burnham and Anderson 1998) for each significant step of the stepwise regression, to prevent over-parameterization of the model. The difference ($\Delta_i$) between a given model and the model with the lowest AICc value is the primary statistic for choosing appropriate models. For biologically realistic models, those with $\Delta_i\leq2$ have substantial support, those in which $4\leq\Delta_i\leq7$ have considerably less support, and models with $\Delta_i>10$ have essentially no support (Burnham and Anderson 2004). Finally, based on the subset of models with the lowest AICc values, determine the best model based on the 5-year and 10-year one-step ahead mean absolute percent error (MAPE).

# References

Burnham, K. P., and D. R. Anderson (1998) Model Selection and Inference. Springer, New York. 353 pp.

Burnham, K. P., and D. R. Anderson (2004) Multimodel inference: Understanding AIC and BIC in model selection. Sociological Methods & Research, Vol. 33(2): 261-304.

Sturdevant, M.V., E.A. Fergusson, J.A. Orsi, and A.C. Wertheimer (2004) Diel feeding and gastric evacuation of juvenile pink and chum salmon in Icy Strait, Southeastern Alaska, May-September 2001. NPAFC Tech. Rep. 5. (Available at http://www.npafc.org).

Wertheimer, A. C., J. A. Orsi, E. A. Fergusson, and M. V. Sturdevant (2010) Calibration of Juvenile Salmon Catches using Paired Comparisons between Two Research Vessels Fishing Nordic 264 Surface Trawls in Southeast Alaska, July 2009. (NPAFC Doc. 1277). Auke Bay Laboratories, Alaska Fish. Sci. Cen., Nat. Mar. Fish. Serv., NOAA, 17109 Point Lena Loop Road, Juneau, 99801, USA, 19 pp. (Available at http://www.npafc.org).

Wertheimer, A. C., J. A. Orsi, and E. A. Fergusson (2015) Forecasting pink salmon harvest in southeast Alaska from juvenile salmon abundance and associated biophysical parameters: 2014 returns and 2015 forecast. NPAFC Doc. 1618. 26 pp. National Oceanic and Atmospheric Administration (NOAA), National Marine Fisheries Service (NMFS), Alaska Fisheries Science Center, Auke Bay Laboratories, Ted Stevens Marine Research Institute (Available at http://www.npafc.org).

Wertheimer, A. C., J. A. Orsi, E. A. Fergusson, and J.M. Murphy (2018) Forecasting pink salmon harvest in Southeast Alaska from juvenile salmon abundance and associated biophysical parameters: 2016 returns and 2017 forecast. NPAFC Doc. 1772. 25 pp. National Oceanic and Atmospheric Administration (NOAA), National Marine Fisheries Service (NMFS), Alaska Fisheries Science Center, Auke Bay Laboratories, Ted Stevens Marine Research Institute (Available at http://www.npafc.org).
